src/python/cloudfoundry_client/main.py, src/python/cloudfoundry_client/v2/applications.py, src/python/cloudfoundry_client/v2/service_plans.py
Really minor stuff seen by pylint...
* quote string to be sure \char is not interpreted
* let the logging module format the string
* NotImplemented is not an exception and supposed to be returned, the exception is NotImplementedError
=> minor corrections from pylint

setup.py, test/python/__init__.py
Make: `python setup.py test` work from the root directory.
The dependencies should be downloaded and installed automatically for the tests if not present, and removed after.
=> make python setup.py test work

src/python/cloudfoundry_client/main.py
I think it is handy to have a simple way to know the version.
The patch could have been:
parser.add_argument('-V', '--version', action='version', version='%(prog)s ' + __version__)
=> add option to see the version

main/cloudfoundry_client/client.py, main/cloudfoundry_client/main.py, requirements.txt
Hi there,
this patch adds the shared_domains and private_domains endpoints and changes the behaviour of the client to use verify in a similar way the underlying requests library uses it. That way it's possible to pass self signed certificates in client code.
Would you take a look and let me know if you're interested in those changes and what would be needed to get them in shape to be merged into the master branch?
Cheers,
Diogo
=> Implement shared and private domains

main/cloudfoundry_client/client.py, requirements.txt
Instead of hard-coding the token endpoint to be {target_endpoint}/oauth/token added an argument to allow customization of the token path so that the token endpoint will be {target_endpoint}{token_path}. This is useful when wanting to provide a login hint to UAA. See https://docs.cloudfoundry.org/api/uaa/version/4.24.0/index.html#browser-flow for other options.
=> CloudFoundryClient: Added token_path to __init__

main/cloudfoundry_client/v2/service_bindings.py, test/v2/test_service_bindings.py
Hi,
It would be convenient (at least for me 😃) if we could specify the name of a binding when creating one.
I've added this possibility in this pull request: the name argument is optional and has been added at the end of the method to avoid breaking existing clients.
Best regards,
Fouad
=> Give the possibility to specify a binding name at creation

main/cloudfoundry_client/v2/apps.py
For equivalent usage of following command : `cf env APP_NAME`
method _Application.env() where _Application type = <class 'cloudfoundry_client.v2.apps._Application'>
=> Add env attribute for _Application

README.rst
Minor improvement to the readme, which contained python 2 and 3 style print statements
=> Improve readme consistency using python3 print

.gitignore, README.rst, main/cloudfoundry_client/client.py, main/cloudfoundry_client/main/main.py, main/cloudfoundry_client/v2/service_plan_visibilities.py, test/fixtures/v2/service_plan_visibilities/GET_response.json, test/fixtures/v2/service_plan_visibilities/GET_{id}_response.json, test/fixtures/v2/service_plan_visibilities/POST_response.json, test/fixtures/v2/service_plan_visibilities/PUT_{id}_response.json, test/v2/test_service_plan_visibilities.py
I added ServicePlanVisibilities To the cf python client
NOTE: the CLI looks little funny because the name is not only the path without the trailing "s" (the "ie" gets "y") I am not sure if we should fix it.
=> Service plan visibilities

README.rst, main/cloudfoundry_client/client.py, main/cloudfoundry_client/main/command_domain.py, main/cloudfoundry_client/main/main.py, main/cloudfoundry_client/v3/buildpacks.py, main/cloudfoundry_client/v3/entities.py, test/fixtures/v3/buildpacks/GET_response.json, test/fixtures/v3/buildpacks/GET_{id}_response.json, test/fixtures/v3/buildpacks/PATCH_{id}_response.json, test/fixtures/v3/buildpacks/POST_response.json, test/v2/test_buildpacks.py, test/v3/test_apps.py, test/v3/test_buildpacks.py, test/v3/test_tasks.py
Hi Ben,
I added the full buildpack functionality for API v3. This includes also the upload functionality of zip files.
* At the moment by default only V2 Entities were used, maybe we change this in the future (at the moment I had direct call "client.v3.buildpacks")
* In this scope I changed the responses of some calls. The reponse object includes in version3 no "entity" and "metadata" field
* With the APIv3 the "update" request will use "patch" not "put"
=> Buildpacks v3

README.rst, main/cloudfoundry_client/rlpgateway/client.py
To be able to use [RLP Gateway](https://github.com/cloudfoundry/loggregator/blob/master/docs/rlp_gateway.md) functionality fully, I've added a possibility to modify requests from RLP client :
- custom headers
- custom params
=> More flexible RLP client

main/cloudfoundry_client/rlpgateway/client.py
I've noticed that in case of huge logs, `iter_any` does not iterate over chunks and does not recognise where the log message ends. As a result, the method would yield just part of the log message at a time. It makes it harder to consume logs.
Iterating through `response.content` ensure yielding one log message (separated by `\n)` at a time.
=> Iterate RLP content

main/cloudfoundry_client/rlpgateway/client.py
Hi,
As it turns out, aiohttp does not handle json streams well. 
Initially, we used `iter_any` to iterate through the logs, but the method implies `\r\n` delimiter (and RLP gateway messages are separated by `\n\n`), so some messages were skipped or merged into one. 
The current solution is iterating through messages separated by `\n`. That should work fine for json streams, however there is a size limitation for messages - 128kb. So, yet again, a few messages are being skipped. The issue is know - [rtfol/aiohttp-sse-client#11](https://github.com/rtfol/aiohttp-sse-client/issues/11), [aio-libs/aiohttp#4453](https://github.com/aio-libs/aiohttp/issues/4453), 
Of course, I would prefer aiohttp to extend the functionality - either add a `separator` argument or a flexible size limit. However, it …
=> Stream reader

main/cloudfoundry_client/client.py
The [_is_token_expired](https://github.com/cloudfoundry-community/cf-python-client/blob/97f334f9853ae935f3b5a6f06948b9661b7562a0/main/cloudfoundry_client/client.py#L186-L196) method does not detect `CF-InvalidAuthToken` errors returned by V3 API endpoints.
Also see [error object](https://v3-apidocs.cloudfoundry.org/version/3.82.0/index.html#errors) in V3 API documentation.
=> Properly detect CF-InvalidAuthToken errors returned by V3 API endpoints

main/cloudfoundry_client/client.py, main/cloudfoundry_client/v3/entities.py, main/cloudfoundry_client/v3/jobs.py, requirements.txt, test/fixtures/v3/jobs/GET_{id}_complete_response.json, test/fixtures/v3/jobs/GET_{id}_failed_response.json, test/fixtures/v3/jobs/GET_{id}_processing_response.json, test/v3/test_buildpacks.py, test/v3/test_jobs.py
**A short explanation of the proposed change:**
We added a v3 JobManager and added a job link to entities in case the 'Location' header is present in the response of the API. The JobManager offers a polling mechanism using the python library 'polling2' to poll jobs until they were processed by the Cloud Controller.
**An explanation of the use cases your change solves:**
When uploading a buildpack using this lib (v3), so far there was no possibility to get back the job url, as the lib didn't extract it from the 'Location' header. Therefore, it was not possible to check whether the buildpack upload was successful or not. With our change the caller will get back the buildpack entitity including a link to the job, which then can be polled using the newly introduced polling functionality of …
=> Add v3 JobManager and job link to entities

main/cloudfoundry_client/v3/apps.py, main/cloudfoundry_client/v3/domains.py, main/cloudfoundry_client/v3/entities.py, test/fixtures/v3/apps/GET_{id}_environment_variables_response.json, test/v3/test_apps.py
Despite name ends with `s`, `environment_variables` link is a single entity instead of a paginate resource
Close #115
=> Fixes generated 'environment_variables' on V3 App entity

requirements.txt
This is used to avoid dependencies conflicts in projects that depend on other packages that require newer protobuf.
Ran tests locally:
=> Allow newer versions of protobuf package

main/cloudfoundry_client/client.py, main/cloudfoundry_client/v3/entities.py, main/cloudfoundry_client/v3/service_instances.py, test/abstract_test_case.py, test/v3/test_service_instances.py
I added an `asynchronous` parameter to provide the possibility to synchronously delete service instances:
```python
cloudfoundry_client.v3.service_instances.remove(service_instance_guid, asynchronous=False)
```
I added a V3 ServiceInstanceManager to add the parameter to the `remove` method.  I use the existing JobManager to poll the job until completed. All other deletion calls are not changed. I also added some tests.
I also fixed a small bug in the `MockResponse` constructor where the headers were not passed along.
In a pipeline and in scripts, it is necessary to wait until an instance has been deleted until e.g. the next service instance is created. Since the v3 API only supports asynchronous deletion, the client has to implement waiting (this feature is also going to be available in …
=> Add synchronous deletion for v3 service instances

main/cloudfoundry_client/client.py, main/cloudfoundry_client/v2/entities.py, main/cloudfoundry_client/v3/entities.py, test/test_client.py
- remove double logging on entities call
- order output such as `PUT - url=http://some-domain.url/any/path/entity - status_code=200 - vcap-request-id=THE-VCAP-REQUEST-ID - body={"the-object": "is here and can be very verbose"}`
=> [refactorings] Log only one line per requests

main/cloudfoundry_client/client.py, test/abstract_test_case.py
This PR changes where the `authorization_endpoint` is retrieved from. Changed from the deprecated endpoint `/info` to `/`.
This PR fixes the issue explained in #128
=> Retrieve UAA endpoint from root rather than /info

README.rst, main/cloudfoundry_client/v3/apps.py, main/cloudfoundry_client/v3/entities.py, test/fixtures/v3/apps/GET_response_include_space.json, test/fixtures/v3/apps/GET_{id}_response_include_space_and_org.json, test/fixtures/v3/spaces/GET_response_include_org.json, test/fixtures/v3/spaces/GET_{id}_response_include_org.json, test/v3/test_apps.py, test/v3/test_spaces.py
Some api endpoints [1] support the inclusion of parent entities. From the currently supported V3 endpoints these are: Apps and Spaces
Added "kwargs" parameter to EntityManager.get; both "get" and "list" can be called with an "include" parameter.
EntityManager._get_url_filtered is now "_get_url_with_encoded_params" and is reused for encoding arbitrary "get" parameters.
EntityManager._read_response calls "_mixin_included_entities" to include the parent entities in the corresponding resource (they are returned in a separate "included" section by the api).
For included entities the Entity constructor overwrites the link method and simply returns the included entity. This is illustrated in the following examples:
The client issues two requests to the api:
- GET /v3/apps/app_id and
- GET …
=> Return included entities

integration/v2/test_applications.py, main/cloudfoundry_client/client.py, main/cloudfoundry_client/operations/push/validation/manifest.py, main/cloudfoundry_client/v3/entities.py
As @andy-paine pointed out in his [commit](https://github.com/cloudfoundry-community/cf-python-client/commit/923c2450772f63d699ed6fced34e04921afbc9c9), the default value returned from `dict.get` is already `None`. So I've removed it everywhere.
=> [Minor] Remove unnecessary default value from dict.get

README.rst, main/cloudfoundry_client/client.py, main/cloudfoundry_client/main/main.py, main/cloudfoundry_client/v3/organization_quotas.py, test/fixtures/v3/organization_quotas/GET_response.json, test/fixtures/v3/organization_quotas/GET_{id}_response.json, test/fixtures/v3/organization_quotas/PATCH_{id}_response.json, test/fixtures/v3/organization_quotas/POST_response.json, test/fixtures/v3/organization_quotas/POST_{id}_organizations_response.json, test/v3/test_organization_quotas.py
This mostly behaves like a normal Entity manager with some additional requirements around updating quota amounts and organizations separately. Using @dataclasses allows for an easy way to take structured arguments for POSTing to CC and should add some helpful type hinting.
JSON examples are copied directly from the V3 API docs
+1 commit to fix README will list of available managers
=> Add organization quota manager + methods

main/cloudfoundry_client/v3/jobs.py
- Due to the PPOLLING state, the only state of waiting is not any more
only PROCESSING, but PROCESSING and POLLING. So we want to check
if state is FAILED or COMPELETE to be sure it finished.
=> Change check_success state to FAILED or COMPLETE

requirements.txt
Dataclasses was introduced with python 3.7. For python 3.6 there is a backport available which can be used. (https://pypi.org/project/dataclasses/)
=> Add missing dataclasses dependency for py 3.6

main/cloudfoundry_client/v3/apps.py, test/v3/test_apps.py
**[Get an app](https://v3-apidocs.cloudfoundry.org/version/3.103.0/index.html#get-an-app)** endpoint doesn't return the restart URL.
Hereby, we can not call the restart URL like this `self.client.v3.apps.get("app_id").restart()`
I added a helper function for the restart URL.
P.S.: **[Get an app](https://v3-apidocs.cloudfoundry.org/version/3.103.0/index.html#get-an-app)** and **[Restart an app](https://v3-apidocs.cloudfoundry.org/version/3.103.0/index.html#restart-an-app)** return same response. Therefore, I used `GET_{id}_response.json` file in the unit test.
=> Restart endpoint added to V3 AppManager

main/cloudfoundry_client/v3/domains.py, main/cloudfoundry_client/v3/organization_quotas.py, test/v3/test_domains.py, test/v3/test_organization_quotas.py
https://v3-apidocs.cloudfoundry.org/version/3.99.0/#create-a-domain show
that the organization/shared_organizations should be embedded in a
`relationships` field. I've added to the test some data for the
shared_organizations to make sure they serialize correctly too
Signed-off-by: Andy Paine <andrew.paine@sap.com>
=> Fix relationships in domain create and org quotas

requirements.txt
Hi,
Here is a PR to pin aiohttp to >= 3.8.0. The reason is HTTP Header Injection vulnerability found in aiohttp: https://security.snyk.io/vuln/SNYK-PYTHON-AIOHTTP-1584144.
Thanks in advance!
=> Pin aiohttp>=3.8.0

main/cloudfoundry_client/client.py, requirements.txt, test/test_client.py
- Bumps oauth2-client to latest version v1.4.0
Including test adoptions to not check authorization header
- Implement `user_agent` parameter of oauth2-client. See https://github.com/antechrestos/OAuth2Client/pull/12
=> Bump oauth2 client & add `user_agent` parameter

main/cloudfoundry_client/v3/service_instances.py, test/fixtures/v3/service_instances/GET_{id}_permissions_response.json, test/v3/test_service_instances.py
https://v3-apidocs.cloudfoundry.org/version/3.138.0/index.html#get-permissions-for-a-service-instance
=> Add support for `GET /v3/service_instances/:guid/permissions`

.github/workflows/pythonpackage.yml, README.rst, dev-requirements.txt, setup.py, test/operations/push/test_push.py, test/v3/test_apps.py
Python 3.7 is End of Life as of June 27th, 2023
Certain dependencies (e.g. `websocket-client`) have already dropped support for Python 3.7 and cannot be updated until support is dropped from this package.
**NOTE**: I guessed the next version (for the README update). Change as needed.
=> Update Supported Python Versions

cloudfoundry_client/v3/entities.py
I encountered this issue while calling the `roles.list` method with the `include` parameter, specifically:
```python
roles = self.client.v3.roles.list(space_guids=[xxx], types=["space_developer", "space_manager", "space_auditor", "space_supporter"], include=["user", "space"])
for role in roles:
user = role.user()
space = role.space()
```
When iterating over the returned `roles` object, I attempted to access the included `user` and `space` data using dynamically generated methods, such as `role.user()` and `role.space()`. However, I noticed that these methods did not return the correct associated data. Instead, both methods returned the same data, corresponding to the last entity processed in the `_included` dictionary.
The problematic line of code is:  
```python
setattr(self, …
```
=> Fix: Ensure correct handling of `_included` entities in `Entity` class

cloudfoundry_client/doppler/client.py, cloudfoundry_client/doppler/websocket_envelope_reader.py, cloudfoundry_client/rlpgateway/client.py
This PR enables using the sdk behind an authenticated proxy.
=> Properly parse proxy urls with credentials in them
