- setup.py
> fix #7: pip install broken by 5e5d45e

- main/cloudfoundry_client/v2/apps.py
makes it compatable w/ python 3.7
> updated the parameter/variable 'async' to 'asynchronous'

- README.rst
- main/cloudfoundry_client/entities.py
- test/test_apps.py
- test/test_entities.py
- test/test_organizations.py
- test/test_routes.py
- test/test_service_bindings.py
- test/test_service_brokers.py
- test/test_service_instances.py
- test/test_service_keys.py
- test/test_service_plans.py
- test/test_services.py
- test/test_spaces.py
Hi.  Thanks for the useful library!  I've improved the query parameter support a bit.  I've got test coverage for what I modified/added and I have tested against a real Cloud Foundry endpoint.
* Properly implement contains queries vs equality queries (` IN ` vs `:`).
* Add support for `order-by` query parameter.
* Add examples to README.
* Add test coverage.
* Fix existing test cases where ` IN ` should be `:` for single value equality.
> Improve query parameter support

- main/cloudfoundry_client/v2/apps.py
Hi Benjamin,
This PR implements the restage functionality for apps using cf-python-client. What do you think of this change? From my initial testing this seems to work but I'd need some advice from you with regards to properly testing this feature.
Btw, what's the recommended way to run the test suite? 
Cheers,
Diogo
> Implement app restage method.

- test/v2/test_apps.py
Hi Benjamin,
you merged my restage changes too fast! Anyway, thanks for that!
Here's a test case I added to exercise the restage functionality.
Thanks!
Diogo
> Add test_restage method

- main/cloudfoundry_client/client.py
Need to be able to retrieve all existing security groups and added that entity to client.py
> Added security_groups entity

- main/cloudfoundry_client/v2/entities.py
- main/cloudfoundry_client/v2/service_instances.py
- test/v2/test_service_instances.py
Adding accepts_incomplete to delete endpoint.
> Adding accepts_incomplete delete/update and purge to delete

- main/cloudfoundry_client/v2/entities.py
- test/fixtures/fake/GET_invalid_entity_with_invalid_entity_type.json
- test/fixtures/fake/GET_invalid_entity_with_null_entity.json
- test/fixtures/fake/GET_invalid_entity_without_entity.json
- test/v2/test_entities.py
This change enforce type checking for entity attribute in object returned
See #56
> Enforce entity attribute check

- main/cloudfoundry_client/client.py
- main/cloudfoundry_client/v3/domains.py
- main/cloudfoundry_client/v3/entities.py
- main/cloudfoundry_client/v3/isolation_segments.py
- main/cloudfoundry_client/v3/spaces.py
- test/fixtures/v3/isolation_segments/GET_response.json
- test/fixtures/v3/isolation_segments/GET_{id}_relationships_organizations_response.json
- test/fixtures/v3/isolation_segments/GET_{id}_relationships_spaces_response.json
- test/fixtures/v3/isolation_segments/GET_{id}_response.json
- test/fixtures/v3/isolation_segments/PATCH_{id}_response.json
- test/fixtures/v3/isolation_segments/POST_response.json
- test/fixtures/v3/isolation_segments/POST_{id}_relationships_organizations_response.json
- test/fixtures/v3/spaces/GET_{id}_relationships_isolation_segment_response.json
- test/fixtures/v3/spaces/POST_response.json
- test/fixtures/v3/spaces/POST_{id}_relationships_isolation_segment_response.json
- test/v3/test_isolation_segments.py
- test/v3/test_spaces.py
> Implement Isoleation Segments V3

- README.rst
- main/cloudfoundry_client/client.py
- main/cloudfoundry_client/rlpgateway/client.py
- requirements.txt
To fix issue #74, I have added a client for RLP Gateway, which has functionality to read application logs directly from gateway.
The official CF documentation can be found [here](https://github.com/cloudfoundry/loggregator/blob/master/docs/rlp_gateway.md).
> RLP gateway client

- README.rst
- main/cloudfoundry_client/rlpgateway/client.py
Some small non-vital but good-to-have changes :)
- Fixed readme so the testing on RLP functionality is possible
- Wrapped async request in RLP client in context manager so that connections are closed properly
> Small fixes for RLP

- main/cloudfoundry_client/client.py
- test/test_client.py
Authentication shall be deduced from `authorization_endpoint` info attribute
> Fix authentication endpoint

- main/cloudfoundry_client/operations/push/push.py
- main/cloudfoundry_client/operations/push/validation/manifest.py
> Fix deprecation warnings due to invalid escape sequences.

- requirements.txt
> Upgrade PyYAML dependency to 5.3.1

- main/cloudfoundry_client/rlpgateway/client.py
RLP gateway sends heartbeat events in case there are no application logs, and those events must be consumed on client side. However, now those messages are skipped.
The change allows to keep the connection alive in case there are no new application logs for more than 15 seconds.
> Keep RLP connection alive

- requirements.txt
Upgrade websocket-client to 0.54
Close #109
> Upgrade websocket version

- requirements.txt
Fixes vulnerability issue #116
> Bumped PyYAML version from 5.3.1 to 5.4.1

- requirements.txt
Remove setuptools from dependency list
See #120
> Clean bad versions in requirements.txt

- main/cloudfoundry_client/client.py
- main/cloudfoundry_client/errors.py
- test/test_client.py
+ tests for logging and error message
> Add Vcap-request-id to error message and debug logging

- main/cloudfoundry_client/client.py
- main/cloudfoundry_client/v3/entities.py
- main/cloudfoundry_client/v3/processes.py
- test/fixtures/v3/processes/GET_response.json
- test/fixtures/v3/processes/GET_{id}_response.json
- test/fixtures/v3/processes/GET_{id}_stats_response.json
- test/v3/test_processes.py
Fixes pagination tests on pagination object to solved #125
> Fixes issues 125

- main/cloudfoundry_client/client.py
- test/test_client.py
Attempt to get login info from
* login section if available
* uaa if available
* self as fallback
Close #135
See [documentation](https://docs.cloudfoundry.org/api/uaa/version/75.4.0/index.html#server-information-2)
> Deduce login information from links

- main/cloudfoundry_client/v3/service_plans.py
* short documentation that points out the difference between PATCH
(replaces/overwrites orgs) and POST (appends orgs)
> Documentation for /v3/service_plans/:guid/visibility

- README.rst
- main/cloudfoundry_client/client.py
- main/cloudfoundry_client/v3/security_groups.py
- test/fixtures/v3/security_groups/GET_response.json
- test/fixtures/v3/security_groups/GET_{id}_response.json
- test/fixtures/v3/security_groups/PATCH_{id}_response.json
- test/fixtures/v3/security_groups/POST_response.json
- test/fixtures/v3/security_groups/POST_{id}_relationships_running_spaces_response.json
- test/fixtures/v3/security_groups/POST_{id}_relationships_staging_spaces_response.json
- test/v3/test_security_groups.py
> Implement security groups in V3 api

- .github/workflows/pythonpackage.yml
- README.rst
- requirements.txt
- setup.py
Stop supporting python 3.6 as its is not supported anymore
> Support python 3.10

- requirements.txt
This passes on all unit tests when run locally.
> Bump pyyaml to 6.0

- README.rst
- main/cloudfoundry_client/client.py
- main/cloudfoundry_client/v3/roles.py
- test/fixtures/v3/roles/GET_response.json
- test/fixtures/v3/roles/GET_{id}_response.json
- test/v3/test_roles.py
> Implement Roles in v3 API

- main/cloudfoundry_client/v2/entities.py
- test/v2/test_entities.py
cf cli supports query filter based on timestamp.
> option to choose a range on timestamp field for /v2/events

- main/cloudfoundry_client/common_objects.py
- main/cloudfoundry_client/json_object.py
- main/cloudfoundry_client/main/command_domain.py
- main/cloudfoundry_client/main/main.py
- main/cloudfoundry_client/main/tasks_command_domain.py
- main/cloudfoundry_client/networking/entities.py
- main/cloudfoundry_client/request_object.py
- main/cloudfoundry_client/v2/apps.py
- main/cloudfoundry_client/v2/entities.py
- main/cloudfoundry_client/v2/jobs.py
- main/cloudfoundry_client/v2/resources.py
- main/cloudfoundry_client/v2/service_plans.py
- main/cloudfoundry_client/v3/apps.py
- main/cloudfoundry_client/v3/domains.py
- main/cloudfoundry_client/v3/entities.py
- test/test_request_object.py
- test/v2/test_entities.py
- test/v3/test_apps.py
- test/v3/test_entities.py
Implement `__len__` for entities manager
> Allow to get number of entities

- main/cloudfoundry_client/operations/push/validation/manifest.py
- test/operations/push/validation/test_manifest_reader.py
> Fixes 'disk_quota' convertion

- main/cloudfoundry_client/client.py
- main/cloudfoundry_client/v2/spaces.py
- test/v2/test_spaces.py
> Implement delete unmapped routes

- requirements.txt
> bump websocket-client to 1.3.1

- requirements.txt
- test/test_client.py
verion 1.4.0 of oauth client was bugged and needs to be upgraded to 1.4.2
Closes #191
> Use new version of oauth client

- requirements.txt
- Add inclusive ordered comparison clause for `PyYAML` package
- `PyYAML` package is now updated to `6.0.1`.
- PR- > https://github.com/yaml/pyyaml/pull/702
- Issue - > https://github.com/yaml/pyyaml/issues/723
> Add inclusive ordered comparison clause for `PyYAML` package

- .github/workflows/pythonpackage.yml
- main/cloudfoundry_client/operations/push/push.py
> fixes(push) fixes host resolution
